FROM cypress/browsers:chrome65-ff57

RUN mkdir /usr/src/app
RUN mkdir -p /usr/src/app/test/E2E/cypress

WORKDIR /usr/src/app

RUN npm install cypress@2.1.0

COPY cypress /usr/src/app/cypress
COPY tests/E2E/cypress/* /usr/src/app/test/E2E/cypress/
COPY cypress.json /usr/src/app/cypress.json

RUN ./node_modules/.bin/cypress verify